language: python
python:
  - "3.7"
  - "3.8"
dist: xenial
services:
  - xvfb

install:
  - pip install -r requirements.txt
  - pip install pytest-qt

script:
  - xvfb-run -a pytest
  - python setup.py sdist
